# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'timer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btimer.proto\x12\x05timer\"A\n\x12\x43onfigTimerRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x1a\n\x12seconds_per_player\x18\x02 \x01(\x05\"=\n\x13\x43onfigTimerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"9\n\x10StartTurnRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tive_color\x18\x02 \x01(\t\"V\n\x11StartTurnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11seconds_remaining\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\"9\n\x10\x43heckTimeRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tive_color\x18\x02 \x01(\t\"Z\n\x11\x43heckTimeResponse\x12\x19\n\x11seconds_remaining\x18\x01 \x01(\x05\x12\x14\n\x0ctime_expired\x18\x02 \x01(\x08\x12\x14\n\x0c\x61\x63tive_color\x18\x03 \x01(\t\"7\n\x0e\x45ndTurnRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tive_color\x18\x02 \x01(\t\"S\n\x0f\x45ndTurnResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cseconds_used\x18\x02 \x01(\x05\x12\x19\n\x11seconds_remaining\x18\x03 \x01(\x05\x32\x8b\x02\n\tTurnTimer\x12>\n\tStartTurn\x12\x17.timer.StartTurnRequest\x1a\x18.timer.StartTurnResponse\x12>\n\tCheckTime\x12\x17.timer.CheckTimeRequest\x1a\x18.timer.CheckTimeResponse\x12\x38\n\x07\x45ndTurn\x12\x15.timer.EndTurnRequest\x1a\x16.timer.EndTurnResponse\x12\x44\n\x0b\x43onfigTimer\x12\x19.timer.ConfigTimerRequest\x1a\x1a.timer.ConfigTimerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGTIMERREQUEST']._serialized_start=22
  _globals['_CONFIGTIMERREQUEST']._serialized_end=87
  _globals['_CONFIGTIMERRESPONSE']._serialized_start=89
  _globals['_CONFIGTIMERRESPONSE']._serialized_end=150
  _globals['_STARTTURNREQUEST']._serialized_start=152
  _globals['_STARTTURNREQUEST']._serialized_end=209
  _globals['_STARTTURNRESPONSE']._serialized_start=211
  _globals['_STARTTURNRESPONSE']._serialized_end=297
  _globals['_CHECKTIMEREQUEST']._serialized_start=299
  _globals['_CHECKTIMEREQUEST']._serialized_end=356
  _globals['_CHECKTIMERESPONSE']._serialized_start=358
  _globals['_CHECKTIMERESPONSE']._serialized_end=448
  _globals['_ENDTURNREQUEST']._serialized_start=450
  _globals['_ENDTURNREQUEST']._serialized_end=505
  _globals['_ENDTURNRESPONSE']._serialized_start=507
  _globals['_ENDTURNRESPONSE']._serialized_end=590
  _globals['_TURNTIMER']._serialized_start=593
  _globals['_TURNTIMER']._serialized_end=860
# @@protoc_insertion_point(module_scope)
