# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import timer_pb2 as timer__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in timer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurnTimerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTurn = channel.unary_unary(
                '/timer.TurnTimer/StartTurn',
                request_serializer=timer__pb2.StartTurnRequest.SerializeToString,
                response_deserializer=timer__pb2.StartTurnResponse.FromString,
                _registered_method=True)
        self.CheckTime = channel.unary_unary(
                '/timer.TurnTimer/CheckTime',
                request_serializer=timer__pb2.CheckTimeRequest.SerializeToString,
                response_deserializer=timer__pb2.CheckTimeResponse.FromString,
                _registered_method=True)
        self.EndTurn = channel.unary_unary(
                '/timer.TurnTimer/EndTurn',
                request_serializer=timer__pb2.EndTurnRequest.SerializeToString,
                response_deserializer=timer__pb2.EndTurnResponse.FromString,
                _registered_method=True)
        self.ConfigTimer = channel.unary_unary(
                '/timer.TurnTimer/ConfigTimer',
                request_serializer=timer__pb2.ConfigTimerRequest.SerializeToString,
                response_deserializer=timer__pb2.ConfigTimerResponse.FromString,
                _registered_method=True)


class TurnTimerServicer:
    """Missing associated documentation comment in .proto file."""

    def StartTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurnTimerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTurn,
                    request_deserializer=timer__pb2.StartTurnRequest.FromString,
                    response_serializer=timer__pb2.StartTurnResponse.SerializeToString,
            ),
            'CheckTime': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTime,
                    request_deserializer=timer__pb2.CheckTimeRequest.FromString,
                    response_serializer=timer__pb2.CheckTimeResponse.SerializeToString,
            ),
            'EndTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.EndTurn,
                    request_deserializer=timer__pb2.EndTurnRequest.FromString,
                    response_serializer=timer__pb2.EndTurnResponse.SerializeToString,
            ),
            'ConfigTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigTimer,
                    request_deserializer=timer__pb2.ConfigTimerRequest.FromString,
                    response_serializer=timer__pb2.ConfigTimerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timer.TurnTimer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('timer.TurnTimer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurnTimer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timer.TurnTimer/StartTurn',
            timer__pb2.StartTurnRequest.SerializeToString,
            timer__pb2.StartTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timer.TurnTimer/CheckTime',
            timer__pb2.CheckTimeRequest.SerializeToString,
            timer__pb2.CheckTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timer.TurnTimer/EndTurn',
            timer__pb2.EndTurnRequest.SerializeToString,
            timer__pb2.EndTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timer.TurnTimer/ConfigTimer',
            timer__pb2.ConfigTimerRequest.SerializeToString,
            timer__pb2.ConfigTimerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
